export enum Events {
    LAUNCH_MINIGAME_EVENT = "LAUNCH_MINIGAME",
    CLOSE_MINIGAME_EVENT = "CLOSE_MINIGAME",
    ASSIGN_ROLE_EVENT = "ASSIGN_ROLE_EVENT",
    ASSIGN_TASK_EVENT = "ASSIGN_TASK_EVENT",
    TASK_COMPLETED_EVENT = "TASK_COMPLETED_EVENT"
}

export enum Tasks {
    BUTTON_PRESS = "button_press_main_deck",
    FEED_POLY = "feed_polly",
}