export enum Events {
    LAUNCH_MINIGAME_EVENT = "LAUNCH_MINIGAME",
    CLOSE_MINIGAME_EVENT = "CLOSE_MINIGAME",
    ASSIGN_ROLE_AND_TASK_EVENT = "ASSIGN_ROLE_AND_TASK_EVENT"
}

export enum Tasks {
    BUTTON_PRESS,
    FEED_POLY,
}